# .github/workflows/release.yml
name: release

on:
  push:
    tags:
      - 'v*' # Run workflow when a tag like v0.1.0 is pushed

jobs:
  goreleaser:
    permissions:
      contents: write # Needed for creating releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for tag analysis

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25' # Use your project's Go version (e.g., 1.21, 1.25)

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}